<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Glance.Capture</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Glance.Core\Glance.Core.csproj" />
  </ItemGroup>
</Project>
